{
 "title": "middleware-2023",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "zone incoming traffic [30s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{dtm_zone=\"cloud\"}[30s]))"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{dtm_zone=\"edge\"}[30s]))"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{dtm_zone=\"mec\"}[30s]))"
    }
   ]
  },
  {
   "title": "zone outgoing traffic [30s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{dtm_zone=\"cloud\"}[30s]))"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{dtm_zone=\"edge\"}[30s]))"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{dtm_zone=\"mec\"}[30s]))"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "pod cpu usage [30s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"digital-twin-.*\"}[30s])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"composed-digital-twin-.*\"}[30s])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod memory (working set) usage [30s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_working_set_bytes{pod=~\"digital-twin-.*\"}[30s])) by (pod)"
    },
    {
     "expr": "sum(rate(container_memory_working_set_bytes{pod=~\"composed-digital-twin-.*\"}[30s])) by (pod)"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "odte",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "dt_odte_value" }
   ]
  },
  {
   "title": "life cycle state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "dt_life_cycle_state" }
   ]
  }
 ]
}