/*
 * webserver
 *
 * rest api
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webserver

// ImplResponse response defines an error code with the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
