/*
 * webserver
 *
 * rest api
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webserver

type Requirements struct {

	// specifies the preferred location deployment along the cloud-to-edge continuum
	PreferredAffinity string `json:"preferredAffinity,omitempty"`

	// sets the threshold below which the app is no longer considered entangled with the physical space. See Overall Digital Twin Entanglement (ODTE)
	Odte float32 `json:"odte,omitempty"`
}

// AssertRequirementsRequired checks if the required fields are not zero-ed
func AssertRequirementsRequired(obj Requirements) error {
	return nil
}

// AssertRecurseRequirementsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Requirements (e.g. [][]Requirements), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRequirementsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRequirements, ok := obj.(Requirements)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRequirementsRequired(aRequirements)
	})
}
