/*
 * webserver
 *
 * rest api
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webserver

// Deployment - provides one ore more config files that describe the overall deployment
type Deployment struct {

	// specifies what to expect in the file(s)
	Type string `json:"type"`

	Affinity string `json:"affinity,omitempty"`

	Configs []Config `json:"configs,omitempty"`
}

// AssertDeploymentRequired checks if the required fields are not zero-ed
func AssertDeploymentRequired(obj Deployment) error {
	elements := map[string]interface{}{
		"type": obj.Type,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Configs {
		if err := AssertConfigRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseDeploymentRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Deployment (e.g. [][]Deployment), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDeploymentRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDeployment, ok := obj.(Deployment)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDeploymentRequired(aDeployment)
	})
}
